name: docker

on: [push]

jobs:
  test:
    name: Build docker
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v2

    - name: Get tag
      id: git_tag
      run: |
        git fetch --prune --unshallow && \
        git describe --abbrev=0 --tags

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: rbsdevelop/burrow:${{ steps.git_tag.outputs }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
